// frontend/src/lib/components/GuideCard.svelte
<script>
  import { cleanTime } from '$lib/utils'
  
  const { guide, isMini } = $props() 

</script>

<div class={`guide-card${isMini ? ' mini' : ''}`}>
  <div>
    <a class="title" href={`/guides/${guide.id}`}>{guide.title} →</a>
		<p class="author muted-text">By {guide.author}</p>
		<p class="created-at muted-text">Created {cleanTime(guide.createdAt)}</p>
		{#if guide.updatedAt !== guide.createdAt}
    <p class="updated-at muted-text">Updated {cleanTime(guide.updatedAt)}</p>
		{/if}
  </div>

	{#if !isMini}
		<div>
			<p class="shortDescription">{guide.shortDescription}...</p>
		</div>
	{/if}
</div>

<style>
  .guide-card {
		padding-bottom: var(--default-spacing);
		margin-top: var(--default-spacing);
		border-bottom: var(--border-width) solid var(--bg-color);
		display: grid;
		grid-template-columns: 1fr 2fr;
		gap: var(--default-spacing);
		height: 200px;
		overflow: hidden;
	}

	.guide-card.mini {
		height: 160px;
		grid-template-columns: 1fr;
	}

	.guide-card.mini div:first-of-type {
		border-right: none;
		padding-right: 0;
	}

	.guide-card div:first-of-type {
		border-right: var(--border-width) solid var(--bg-color);
		padding-right: var(--default-spacing);
	}
	.guide-card:first-of-type {
		margin-top: 0;
	}
	.guide-card:last-of-type {
		padding-bottom: 0;
		border-bottom: none;
	}
	.guide-card .title {
		font-size: 1.35em;
	}
</style>

// frontend/src/components/GuideCard.jsx
import './GuideCard.css'
import { cleanTime } from '../utils'

const GuideCard = (props) => {
  return (
    <div className={`GuideCard${props.isMini ? ' mini' : ''}`}>
      <div>
        <a className="title" href={`/guides/${props.guide.id}`}>
          {props.guide.title} →
        </a>
        <p className="author muted-text">By {props.guide.author}</p>
        <p className="created-at muted-text">
          Created {cleanTime(props.guide.createdAt)}
        </p>
        {props.guide.updatedAt !== props.guide.createdAt && (
          <p className="updated-at muted-text">
            Updated {cleanTime(props.guide.updatedAt)}
          </p>
        )}
      </div>

      {!props.isMini && (
        <div>
          <p className="shortDescription">{props.guide.shortDescription}...</p>
        </div>
      )}
    </div>
  )
}

export default GuideCard
