// frontend/src/routes/Guides.jsx
import './Guides.css'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getAllGuides, getGuidesByTitle } from '../services/guides'
import Panel from '../components/ui/Panel'
import GuideCard from '../components/GuideCard'

const Guides = () => {
  const [guides, setGuides] = useState([])

  const getGuides = async () => {
    try {
      const allGuides = await getAllGuides()

      setGuides(allGuides)
    } catch (error) {
      console.log(error.message)
    }
  }

  const onSearch = async (event) => {
    event.preventDefault()

    const res = await getGuidesByTitle(search)
    setGuides(res.guides)
  }

  useEffect(() => {
    getGuides()
  }, [])

  return (
    <div>
      <header>
        <h1>Guides</h1>

        <div>
          <form className="search" onSubmit={(event) => onSearch(event)}>
            <label htmlFor="search"></label>
            <input
              id="search"
              type="text"
              name="search"
              placeholder="Search by title..."
            />

            <button className="search">Search</button>
          </form>
        </div>

        <div>
          <Link to="/guides/new" className="btn">
            Create Guide
          </Link>
        </div>
      </header>

      <Panel>
        {guides && guides.length > 0 ? (
          guides.map((g) => {
            ;<GuideCard guide={g} key={g.id} />
          })
        ) : (
          <p>No guides found!</p>
        )}
      </Panel>
    </div>
  )
}

export default Guides

// frontend/src/routes/guides/+page.svelte
<script>
  import { getGuidesByTitle } from '$lib/services/guides'
  import Panel from '$lib/components/ui/Panel.svelte'
  import GuideCard from '$lib/components/GuideCard.svelte'

  let { data } = $props()
  let guides = $state(data.guides)
  let search = $state('')

  const onSearch = async (event) => {
    event.preventDefault()

    const res = await getGuidesByTitle(search)
    guides = res.guides
  }

</script>

<header>
  <h1>Guides</h1>

  <div>
    <form onsubmit={(event) => onSearch(event)}>
      <label for="search"></label>
      <input 
        id="search"
        type="text"
        name="search"
        placeholder="Search by title..."
        bind:value={search}
      />

      <button class="search">Search</button>
    </form>
  </div>

  <div>
    <a class="btn" href="/guides/new">Create Guide</a>
  </div>
</header>

<Panel>
  {#await guides}
    <p class="msg">Loading guides...</p>
  {:then guides}
    {#if guides && guides.length > 0}
      {#each guides as g}
        <GuideCard guide={g} />
      {/each}
    {:else}
      <p class="msg">There are no guides!</p>
    {/if}
  {:catch error}
    <p class="error">An error occurred: {error.message}</p>
  {/await}
</Panel>

<style>
  form {
    display: flex;
  }
</style>
